language: cpp
dist: bionic
compiler: gcc
os: linux
env:
    - CXX_STANDARD=c++17
addons:
  apt:
    sources:
         - boost-latest
before_install:
- sudo apt-get update
- sudo apt-get install libboost-all-dev boost-build
- cmake .
- make
- ./findncopy -h
- ./trim -h
- ./threshold -h
branches:
  only:
      - master
notifications:
  email: false

